# Site settings
title: Luca Faggianelli

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lucafaggianelli.github.io"
img_url: "/images"

twitter_username: lucafaggianelli
github_username:  lucafaggianelli
linkedin_username:  lucafaggianelli

# Build settings
markdown: kramdown
exclude: [admin]

# Posts permalink style
permalink: '/:title.html'

analytics_tracking_id: 'UA-76822752-1'
